# Generated by Django 5.0.2 on 2024-05-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0002_threedprinter_threedprinteruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='threedprinter',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
