# Generated by Django 5.0.6 on 2024-05-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0003_threedprinter_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='threedprinteruser',
            name='com_port',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='threedprinteruser',
            name='ip_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
